### ISSUE TITLE
Allow states to be any immutable object (not just strings)

### ISSUE THREAD

**Issue by tchaumeny** [rohaquinlop/automathon#14]
Thanks for your library that I have used to illustrate an article about DFA (see [here](https://lipsum.dev/2024-01-1-automates-regex-presburger/))!

I actually wanted to use integers to define the states and I found that this is not possible (it fails when calling `automata.view(...)`), is there any specific reason for this restriction?

It seems that any hashable object could be a state and the graphviz representation could just use `str()`.

**Comment by rohaquinlop** [comment]
Hey Thomas! Thank you so much for using automathon and the mention on your article.

In the implementation, I tried to keep it the simplest as possible and as in the book [Automata and Computability](https://link.springer.com/book/10.1007/978-1-4612-1844-9) there are many examples using `q0` or `s1` and so on as states names then implemented all the states as strings.

Right now I'm working on a change to use the python typing and make it like "strict" to use the parameters types as are defined, I don't know if using any immutable object will make fail any other algorithms that are implemented since I'm always assuming that the states are strings also the keys on the delta map.

Once again, thank you for using automathon and letting me know your ideas.
